apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  - image: staffofhades/ticketing
    docker:
      dockerfile: dev.Dockerfile
    sync:
      manual:
      - src: "apps/authentication/src/**/*.{js,ts}"
        dest: .
      - src: "apps/ticketing/src/**/*.{css,sass,scss}"
        dest: .
      - src: "apps/ticketing/src/**/*.{js,jsx,ts,tsx}"
        dest: .
      - src: "apps/ticketing/src/**/*.html"
        dest: .
      - src: "libs/**/*.{js,ts}"
        dest: .
      - src: "**/tsconfig.{*}.json"
        dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s/development/*.yaml
    - infra/k8s/authentication-mongo-depl.yaml
    - infra/k8s/ingress-srv.yaml
