apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: staffofhades/ticketing
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: 'apps/{authentication,tickets}-service/src/**/*.{js,ts}'
            dest: .
          - src: 'apps/ticketing/{components,pages}/**/*.{css,sass,scss}'
            dest: .
          - src: 'apps/ticketing/{components,hooks,pages,specs}/**/*.{js,jsx,ts,tsx}'
            dest: .
          - src: 'libs/**/*.{js,jsx,ts,tsx}'
            dest: .
          - src: '**/tsconfig.*.json'
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/development/*.yaml
      - infra/k8s/authentication-mongo-depl.yaml
      - infra/k8s/nats-depl.yaml
      - infra/k8s/tickets-mongo-depl.yaml
