apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-services-srv
spec:
  ingressClassName: nginx
  rules:
  - host: ticketing.dev
    http:
      paths:
      - path: /authentication-service(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: authentication-clusterip-srv
            port:
              number: 3000
